server:
  port: 9765
spring:
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
      